<a href="https://colab.research.google.com/github/nayankhanal/ml-class/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('employees.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'employees.csv'

In [ ]:
df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB

In [ ]:
df['Start Date'] = pd.to_datetime(df['Start Date'], format='%m/%d/%Y')

# we can also do this, by applying same thing while reading csv
# df = pd.read_csv('employees.csv', parse_dates=['Start Date'], date_format='%m/%d/%Y')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   datetime64[ns]
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 62.6+ KB

In [ ]:
df['Last Login Time'] = pd.to_datetime(df['Last Login Time'], format='%I:%M %p')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   datetime64[ns]
 3   Last Login Time    1000 non-null   datetime64[ns]
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: datetime64[ns](2), float64(1), int64(1), object(4)
memory usage: 62.6+ KB

In [ ]:
import datetime as dt

In [ ]:
df[df['Last Login Time'].dt.time > dt.time(12,0)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,1900-01-01 12:42:00,97308,6.945,True,Marketing
34,Jerry,Male,2004-01-10,1900-01-01 12:56:00,95734,19.096,False,Client Services
49,Chris,NaN,1980-01-24,1900-01-01 12:13:00,113590,3.055,False,Sales
61,Denise,Female,2001-11-06,1900-01-01 12:03:00,106862,3.699,False,Business Development
76,Margaret,Female,1988-09-10,1900-01-01 12:42:00,131604,7.353,True,Distribution
...,...,...,...,...,...,...,...,...
945,Gerald,NaN,1989-04-15,1900-01-01 12:44:00,93712,17.426,True,Distribution
956,Beverly,Female,1986-10-17,1900-01-01 12:51:00,80838,8.115,False,Engineering
962,Jonathan,Male,2013-08-21,1900-01-01 12:45:00,121797,16.923,False,Product
980,Kimberly,Female,2013-01-26,1900-01-01 12:57:00,46233,8.862,True,Engineering
997,Russell,Male,2013-05-20,1900-01-01 12:39:00,96914,1.421,False,Product

In [ ]:
df[df['Salary'].between(60000,70000)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,1900-01-01 06:53:00,61933,4.170,True,NaN
6,Ruby,Female,1987-08-17,1900-01-01 04:20:00,65476,10.012,True,Product
10,Louise,Female,1980-08-12,1900-01-01 09:01:00,63241,15.132,True,NaN
20,Lois,NaN,1995-04-22,1900-01-01 07:18:00,64714,4.934,True,Legal
41,Christine,NaN,2015-06-28,1900-01-01 01:08:00,66582,11.308,True,Business Development
...,...,...,...,...,...,...,...,...
965,Catherine,Female,1989-09-25,1900-01-01 01:31:00,68164,18.393,False,Client Services
970,Alice,Female,1988-09-03,1900-01-01 08:54:00,63571,15.397,True,Product
974,Harry,Male,2011-08-30,1900-01-01 06:31:00,67656,16.455,True,Client Services
978,Sean,Male,1983-01-17,1900-01-01 02:23:00,66146,11.178,False,Human Resources
998,Larry,Male,2013-04-20,1900-01-01 04:45:00,60500,11.985,False,Business Development

In [ ]:
df[df['Team'].isin(['Marketing'])]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,1900-01-01 12:42:00,97308,6.945,True,Marketing
21,Matthew,Male,1995-09-05,1900-01-01 02:12:00,100612,13.645,False,Marketing
26,Craig,Male,2000-02-27,1900-01-01 07:45:00,37598,7.757,True,Marketing
43,Marilyn,Female,1980-12-07,1900-01-01 03:16:00,73524,5.207,True,Marketing
62,NaN,Female,2007-06-12,1900-01-01 05:25:00,58112,19.414,NaN,Marketing
...,...,...,...,...,...,...,...,...
942,Lori,Female,2015-11-20,1900-01-01 01:15:00,75498,6.537,True,Marketing
947,NaN,Male,2012-07-30,1900-01-01 03:07:00,107351,5.329,NaN,Marketing
986,Donna,Female,1982-11-26,1900-01-01 07:04:00,82871,17.999,False,Marketing
991,Rose,Female,2002-08-25,1900-01-01 05:12:00,134505,11.051,True,Marketing
994,George,Male,2013-06-21,1900-01-01 05:47:00,98874,4.479,True,Marketing

In [ ]:
df[df['Gender'].duplicated(keep='first')] # first is defaut, we can give last too, keep=False will filter duplicated ones

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,1900-01-01 06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,1900-01-01 01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,1900-01-01 04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,1900-01-01 01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,1900-01-01 04:20:00,65476,10.012,True,Product
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,1900-01-01 06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,1900-01-01 06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,1900-01-01 12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,1900-01-01 04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,1900-01-01 06:24:00,129949,10.169,True,Sales

In [ ]:
df.drop_duplicates("Team", keep='last')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
951,NaN,Female,2010-09-14,1900-01-01 05:19:00,143638,9.662,NaN,NaN
988,Alice,Female,2004-10-05,1900-01-01 09:34:00,47638,11.209,False,Human Resources
989,Justin,NaN,1991-02-10,1900-01-01 04:58:00,38344,3.794,False,Legal
990,Robin,Female,1987-07-24,1900-01-01 01:35:00,100765,10.982,True,Client Services
993,Tina,Female,1997-05-15,1900-01-01 03:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,1900-01-01 05:47:00,98874,4.479,True,Marketing
995,Henry,NaN,2014-11-23,1900-01-01 06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,1900-01-01 06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,1900-01-01 12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,1900-01-01 04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,1900-01-01 06:24:00,129949,10.169,True,Sales

In [ ]:
df.drop_duplicates(["Team","First Name"], keep='last')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,1900-01-01 06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,1900-01-01 11:17:00,130590,11.858,False,Finance
4,Larry,Male,1998-01-24,1900-01-01 04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,1900-01-01 01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,1900-01-01 04:20:00,65476,10.012,True,Product
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,1900-01-01 06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,1900-01-01 06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,1900-01-01 12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,1900-01-01 04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,1900-01-01 06:24:00,129949,10.169,True,Sales

In [ ]:
df["Team"].unique()

array(['Marketing', nan, 'Finance', 'Client Services', 'Legal', 'Product',
       'Engineering', 'Business Development', 'Human Resources', 'Sales',
       'Distribution'], dtype=object)

In [ ]:
df[df['Team'].isnull()].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,1900-01-01 06:53:00,61933,4.170,True,NaN
10,Louise,Female,1980-08-12,1900-01-01 09:01:00,63241,15.132,True,NaN
23,NaN,Male,2012-06-14,1900-01-01 04:19:00,125792,5.042,NaN,NaN
32,NaN,Male,1998-08-21,1900-01-01 02:27:00,122340,6.417,NaN,NaN
91,James,NaN,2005-01-26,1900-01-01 11:00:00,128771,8.309,False,NaN