<a href="https://colab.research.google.com/github/nayankhanal/ml-class/blob/main/time_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('sales.csv')

In [3]:
df.head()

         date  store  item  sales
0  2013-01-01      1     1     13
1  2013-01-02      1     1     11
2  2013-01-03      1     1     14
3  2013-01-04      1     1     13
4  2013-01-05      1     1     10

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 913000 entries, 0 to 912999
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    913000 non-null  object
 1   store   913000 non-null  int64
 2   item    913000 non-null  int64
 3   sales   913000 non-null  int64
dtypes: int64(3), object(1)
memory usage: 27.9+ MB

# Date Based Features
# Lag Features  --> Lag1

'''
Date. Sales. Lag1. Lag2
Jan1.   13.   NaN.  NaN
Jan2.   11.   13.  NaN
Jan3.   14.   11.   13
'''

# Rolling Statistics

'''
3-day rolling mean

Sales
13
11
14

(12+11+14) / 3
'''


# Rolling Min

'''
12 11 14 15 17 --> 11
'''


# Rolling Max

'''
12 11 14 15 17 --> 17
'''


# Rolling Standard Deviation

'''
Stable - 10,11,10,11. --> Hign chance for 10 for next day
Volatine - 2,20,5,25
'''

# Difference Features

'''
Sales.  Diff
13.      NaN
11       -2
14       +3
'''


# Percentage Change

'''
(Today - Yesterday) / Yesterday
(14 - 11) / 11
'''


# Seasonal Features --> dat_of_week, month, quarter

# Cyclical -> Sunday=6, Monday=0, sin(day), cos(day)

# Trend Features --> Model Learnins upward or downward

In [6]:
df['date'] = pd.to_datetime(df['date'])
df['date']

0        2013-01-01
1        2013-01-02
2        2013-01-03
3        2013-01-04
4        2013-01-05
            ...
912995   2017-12-27
912996   2017-12-28
912997   2017-12-29
912998   2017-12-30
912999   2017-12-31
Name: date, Length: 913000, dtype: datetime64[ns]

In [12]:
df['date'].dt.year

0         2013
1         2013
2         2013
3         2013
4         2013
          ...
912995    2017
912996    2017
912997    2017
912998    2017
912999    2017
Name: date, Length: 913000, dtype: int32

In [13]:
df = df.sort_values('date')
df

             date  store  item  sales
0      2013-01-01      1     1     13
211816 2013-01-01      7    12     26
832656 2013-01-01      7    46     27
213642 2013-01-01      8    12     54
215468 2013-01-01      9    12     35
...           ...    ...   ...    ...
619013 2017-12-31      9    34     21
620839 2017-12-31     10    34     32
622665 2017-12-31      1    35     55
598927 2017-12-31      8    33    100
912999 2017-12-31     10    50     82

[913000 rows x 4 columns]

In [14]:
df.sample()

             date  store  item  sales
419712 2017-04-08     10    23     40

In [15]:
df['month'] = df['date'].dt.month
df.sample()

             date  store  item  sales  month
332455 2013-05-04      3    19     56      5

In [19]:
df['day'] = df['date'].dt.day
df.sample()

             date  store  item  sales  month  day  year
433545 2015-02-23      8    24     56      2   23  2015

In [20]:
df['year'] = df['date'].dt.year
df.sample()

             date  store  item  sales  month  day  year
593569 2013-04-30      6    33     47      4   30  2013

In [22]:
df['dayofweek'] = df['date'].dt.dayofweek # Mon = 0, Tues = 1 ...... Sun = 6
df.sample()

            date  store  item  sales  month  day  year  dayofweek
38436 2013-04-01      2     3     25      4    1  2013          0

In [23]:
df['weekofyear'] = df['date'].dt.isocalendar().week
df.sample(5)

             date  store  item  sales  month  day  year  dayofweek  weekofyear
553063 2017-05-31      3    31     90      5   31  2017          2          22
225058 2014-04-06      4    13     99      4    6  2014          6          14
2129   2013-10-31      2     1     34     10   31  2013          3          44
138548 2017-05-18      6     8     66      5   18  2017          3          20
649516 2016-07-10      6    36    108      7   10  2016          6          27

In [24]:
df['quarter'] = df['date'].dt.quarter
df.sample(5)

,date,store,item,sales,month,day,year,dayofweek,weekofyear,quarter
21207,2016-01-27,2,2,57,1,27,2016,2,4,1
633375,2017-04-29,7,35,58,4,29,2017,5,17,2
322358,2015-09-10,7,18,53,9,10,2015,3,37,3
156124,2015-07-04,6,9,67,7,4,2015,5,27,3
330061,2016-10-13,1,19,32,10,13,2016,3,41,4

In [25]:
df['is_weekend'] = (df['dayofweek'] >=5 ).astype(int)
df.sample(5)

,date,store,item,sales,month,day,year,dayofweek,weekofyear,quarter,is_weekend
848337,2015-12-10,5,47,13,12,10,2015,3,50,4,0
892848,2017-10-27,9,49,49,10,27,2017,4,43,4,0
220572,2016-12-23,1,13,65,12,23,2016,4,51,4,0
620199,2016-03-31,10,34,25,3,31,2016,3,13,1,0
374297,2017-11-29,5,21,40,11,29,2017,2,48,4,0

In [26]:
# Lag Features

In [27]:
df.head()

,date,store,item,sales,month,day,year,dayofweek,weekofyear,quarter,is_weekend
0,2013-01-01,1,1,13,1,1,2013,1,1,1,0
211816,2013-01-01,7,12,26,1,1,2013,1,1,1,0
832656,2013-01-01,7,46,27,1,1,2013,1,1,1,0
213642,2013-01-01,8,12,54,1,1,2013,1,1,1,0
215468,2013-01-01,9,12,35,1,1,2013,1,1,1,0

In [28]:
df['lag_1'] = df['sales'].shift(1)
df.head(5)

,date,store,item,sales,month,day,year,dayofweek,weekofyear,quarter,is_weekend,lag_1
0,2013-01-01,1,1,13,1,1,2013,1,1,1,0,NaN
211816,2013-01-01,7,12,26,1,1,2013,1,1,1,0,13.0
832656,2013-01-01,7,46,27,1,1,2013,1,1,1,0,26.0
213642,2013-01-01,8,12,54,1,1,2013,1,1,1,0,27.0
215468,2013-01-01,9,12,35,1,1,2013,1,1,1,0,54.0

In [30]:
df['lag_7'] = df['sales'].shift(7)
df.head(8)

,date,store,item,sales,month,day,year,dayofweek,weekofyear,quarter,is_weekend,lag_1,lag_7
0,2013-01-01,1,1,13,1,1,2013,1,1,1,0,NaN,NaN
211816,2013-01-01,7,12,26,1,1,2013,1,1,1,0,13.0,NaN
832656,2013-01-01,7,46,27,1,1,2013,1,1,1,0,26.0,NaN
213642,2013-01-01,8,12,54,1,1,2013,1,1,1,0,27.0,NaN
215468,2013-01-01,9,12,35,1,1,2013,1,1,1,0,54.0,NaN
217294,2013-01-01,10,12,41,1,1,2013,1,1,1,0,35.0,NaN
830830,2013-01-01,6,46,23,1,1,2013,1,1,1,0,41.0,NaN
219120,2013-01-01,1,13,37,1,1,2013,1,1,1,0,23.0,13.0

In [32]:
df['sales'].shift(1).rolling(3).mean()

0               NaN
211816          NaN
832656          NaN
213642    22.000000
215468    35.666667
            ...
619013    27.666667
620839    27.333333
622665    32.000000
598927    36.000000
912999    62.333333
Name: sales, Length: 913000, dtype: float64

In [33]:
df['diff_1'] = df['sales'].diff(1)
df.head()

,date,store,item,sales,month,day,year,dayofweek,weekofyear,quarter,is_weekend,lag_1,lag_7,diff_1
0,2013-01-01,1,1,13,1,1,2013,1,1,1,0,NaN,NaN,NaN
211816,2013-01-01,7,12,26,1,1,2013,1,1,1,0,13.0,NaN,13.0
832656,2013-01-01,7,46,27,1,1,2013,1,1,1,0,26.0,NaN,1.0
213642,2013-01-01,8,12,54,1,1,2013,1,1,1,0,27.0,NaN,27.0
215468,2013-01-01,9,12,35,1,1,2013,1,1,1,0,54.0,NaN,-19.0

In [35]:
df['pct_change'] = df['sales'].pct_change() * 100
df.head()

,date,store,item,sales,month,day,year,dayofweek,weekofyear,quarter,is_weekend,lag_1,lag_7,diff_1,pct_change
0,2013-01-01,1,1,13,1,1,2013,1,1,1,0,NaN,NaN,NaN,NaN
211816,2013-01-01,7,12,26,1,1,2013,1,1,1,0,13.0,NaN,13.0,100.000000
832656,2013-01-01,7,46,27,1,1,2013,1,1,1,0,26.0,NaN,1.0,3.846154
213642,2013-01-01,8,12,54,1,1,2013,1,1,1,0,27.0,NaN,27.0,100.000000
215468,2013-01-01,9,12,35,1,1,2013,1,1,1,0,54.0,NaN,-19.0,-35.185185