<a href="https://colab.research.google.com/github/nayankhanal/ml-class/blob/vs-code/pytorch/rnn_based_qa_system_class_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [185]:
import pandas as pd

In [186]:
df = pd.read_csv("100_Unique_QA_Dataset.csv")

In [187]:
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [188]:
df['question'], df['answer'] = df['question'].str.lower(), df['answer'].str.lower()

In [189]:
import re

In [190]:
df[['question', 'answer']] = df[['question', 'answer']].apply(lambda col: col.str.replace(r'<.*?>', '', regex=True))

In [191]:
url_pattern = r'http[s]?://\S+|www\.\S+'

df['question'] = df['question'].str.replace(url_pattern, '', regex=True)
df['answer'] = df['answer'].str.replace(url_pattern, '', regex=True)

In [192]:
import string

punct_pattern = f'[{string.punctuation}]'

df['question'] = df['question'].str.replace(punct_pattern, ' ', regex=True)
# df['answer'] = df['answer'].str.replace(punct_pattern, ' ', regex=True)

In [193]:
# pip install pyspellchecker

In [194]:
from spellchecker import SpellChecker

spell = SpellChecker()

misspelled_words = set()

def find_misspelled(text):
  words = text.split()
  unknown = spell.unknown(words)
  misspelled_words.update(unknown)

In [195]:
df['question'].apply(find_misspelled)
# df['answer'].apply(find_misspelled)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Name: question, Length: 90, dtype: object

In [196]:
misspelled_words

{'ii', 'tv', 'uk'}

In [197]:
# pip install emoji

In [198]:
import emoji

emoji_list = []

def find_emojis(text):
    found = emoji.emoji_list(text)
    for item in found:
        emoji_list.append(item['emoji'])

df['question'].apply(find_emojis)
df['answer'].apply(find_emojis)

print(emoji_list)

[]

In [199]:
# import emoji

# def handle_emojis(text):
#     return emoji.demojize(text)

# df['question'] = df['question'].apply(handle_emojis)
# df['answer'] = df['answer'].apply(handle_emojis)

In [200]:
df.head()

                                          question      answer
0                   what is the capital of france        paris
1                  what is the capital of germany       berlin
2               who wrote  to kill a mockingbird    harper-lee
3  what is the largest planet in our solar system      jupiter
4   what is the boiling point of water in celsius          100

In [201]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [202]:
nltk.word_tokenize(df['question'][0])

['what', 'is', 'the', 'capital', 'of', 'france']

In [203]:
# vocab
vocab = {'<UNK>':0}

In [204]:
def build_vocab(row):
  tokenized_question = nltk.word_tokenize(row['question'])
  tokenized_answer = nltk.word_tokenize(row['answer'])

  merged_tokens = tokenized_question + tokenized_answer

  for token in merged_tokens:
    if token not in vocab:
      vocab[token] = len(vocab)

In [205]:
df.apply(build_vocab, axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [206]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 '1984': 67,
 'george-orwell': 68,
 'currency': 69,
 'united': 70,
 'kingdom': 71,
 'pound': 72,
 'india': 73,
 'delhi': 74,
 'discovered': 75,
 'gravity': 76,
 'newton': 77,
 'how': 78,
 'many': 79,
 'continents': 80,
 'are': 81,
 'there': 82,
 'on': 83,
 'earth': 84,
 '7': 85,
 'gas': 86,
 'do': 87,
 'plants': 88,
 'use': 89,
 'photosynthesis': 90,
 'co2': 91,
 'smallest': 92,
 'prime': 93,
 'number': 94,
 '2': 95,
 'invented': 96,
 'telephone': 97,
 'alexander-graham-bell': 98,
 'australia': 99,
 'canberra': 100,
 'ocean': 101,
 'pacific-ocean': 102,
 'speed': 103,
 'light': 104,
 'vacuum': 105,
 '299,792,458m/s': 106,
 'language': 107,
 'spoken': 108,
 'brazil': 109,
 'portuguese': 110,
 'penicillin': 111,
 'alexander-fleming': 112,
 'canada': 113,
 'ottawa': 114,
 'mammal': 115,
 'whale': 116,
 'element': 117,
 'has': 118,
 'atomic': 119,
 '1': 120,
 'hydrogen': 121,
 'tallest': 122,
 'mountain': 123,
 'everest': 124,
 'city': 125,
 'big': 126,
 'apple': 127,
 'newyork': 128,
 'planets': 129,
 'starry': 130,
 'night': 131,
 'vangogh': 132,
 'formula': 133,
 'h2o': 134,
 'italy': 135,
 'rome': 136,
 'country': 137,
 'famous': 138,
 'sushi': 139,
 'was': 140,
 'first': 141,
 'person': 142,
 'step': 143,
 'moon': 144,
 'armstrong': 145,
 'main': 146,
 'ingredient': 147,
 'guacamole': 148,
 'avocado': 149,
 'sides': 150,
 'does': 151,
 'hexagon': 152,
 'have': 153,
 '6': 154,
 'china': 155,
 'yuan': 156,
 'pride': 157,
 'and': 158,
 'prejudice': 159,
 'jane-austen': 160,
 'iron': 161,
 'fe': 162,
 'hardest': 163,
 'natural': 164,
 'substance': 165,
 'diamond': 166,
 'continent': 167,
 'by': 168,
 'area': 169,
 'asia': 170,
 'president': 171,
 'states': 172,
 'george-washington': 173,
 'bird': 174,
 'its': 175,
 'ability': 176,
 'mimic': 177,
 'sounds': 178,
 'parrot': 179,
 'running': 180,
 'animated': 181,
 'tv': 182,
 'show': 183,
 'simpsons': 184,
 'vaticancity': 185,
 'most': 186,
 'moons': 187,
 'saturn': 188,
 'romeo': 189,
 'juliet': 190,
 'shakespeare': 191,
 's': 192,
 'atmosphere': 193,
 'nitrogen': 194,
 'bones': 195,
 'adult': 196,
 'human': 197,
 'body': 198,
 '206': 199,
 'metal': 200,
 'liquid': 201,
 'at': 202,
 'room': 203,
 'temperature': 204,
 'mercury': 205,
 'russia': 206,
 'moscow': 207,
 'electricity': 208,
 'benjamin-franklin': 209,
 'second': 210,
 'land': 211,
 'color': 212,
 'ripe': 213,
 'banana': 214,
 'yellow': 215,
 'month': 216,
 '28': 217,
 'days': 218,
 'common': 219,
 'february': 220,
 'study': 221,
 'living': 222,
 'organisms': 223,
 'called': 224,
 'biology': 225,
 'home': 226,
 'great': 227,
 'wall': 228,
 'bees': 229,
 'collect': 230,
 'from': 231,
 'flowers': 232,
 'nectar': 233,
 'opposite': 234,
 'day': 235,
 'south': 236,
 'korea': 237,
 'seoul': 238,
 'bulb': 239,
 'edison': 240,
 'humans': 241,
 'breathe': 242,
 'survival': 243,
 'oxygen': 244,
 '144': 245,
 '12': 246,
 'pyramids': 247,
 'giza': 248,
 'egypt': 249,
 'sea': 250,
 'creature': 251,
 'eight': 252,
 'arms': 253,
 'octopus': 254,
 'holiday': 255,
 'celebrated': 256,
 'december': 257,
 '25': 258,
 'christmas': 259,
 'yen': 260,
 'legs': 261,
 'spider': 262,
 'sport': 263,
 'uses': 264,
 'net': 265,
 'ball': 266,
 'hoop': 267,
 'basketball': 268,
 'kangaroos': 269,
 'female': 270,
 'minister': 271,
 'uk': 272,
 'margaretthatcher': 273,
 'fastest': 274,
 'animal': 275,
 'cheetah': 276,
 'periodic': 277,
 'table': 278,
 'spain': 279,
 'madrid': 280,
 'closest': 281,
 'sun': 282,
 'father': 283,
 'computers': 284,
 'charlesbabbage': 285,
 'mexico': 286,
 'mexicocity': 287,
 'colors': 288,
 'rainbow': 289,
 'musical': 290,
 'instrument': 291,
 'black': 292,
 'white': 293,
 'keys': 294,
 'piano': 295,
 'americas': 296,
 '1492': 297,
 'christophercolumbus': 298,
 'disney': 299,
 'character': 300,
 'long': 301,
 'nose': 302,
 'grows': 303,
 'it': 304,
 'when': 305,
 'lying': 306,
 'pinocchio': 307,
 'directed': 308,
 'movie': 309,
 'titanic': 310,
 'jamescameron': 311,
 'superhero': 312,
 'also': 313,
 'dark': 314,
 'knight': 315,
 'batman': 316,
 'brasilia': 317,
 'fruit': 318,
 'king': 319,
 'fruits': 320,
 'mango': 321,
 'eiffel': 322,
 'tower': 323}

In [207]:
len(vocab)

324

In [242]:
# convert words to numerical indices
def text_to_indices(text, vocab):
  indexed_text = []

  text = text.lower()
  text = re.sub(punct_pattern, ' ', text)

  for token in nltk.word_tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text

In [209]:
text_to_indices("What is campusx", vocab)

[1, 2, 0]

In [210]:
import torch
from torch.utils.data import Dataset, DataLoader

In [211]:
class QADataset(Dataset):
  def __init__(self, df, vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self, index):
    numerical_questions = text_to_indices(self.df.iloc[index]['question'], self.vocab)
    numerical_answers = text_to_indices(self.df.iloc[index]['answer'], self.vocab)

    return torch.tensor(numerical_questions), torch.tensor(numerical_answers)

In [212]:
dataset = QADataset(df, vocab)

In [213]:
dataloader = DataLoader(dataset, batch_size=1, shuffle=True)

In [214]:
for question, answer in dataloader:
  print(question, answer[0])

tensor([[10, 55,  3, 56,  5, 57]]) tensor([58])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([106])
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([134])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([7])
tensor([[ 42, 263, 264,  14, 265, 266, 158, 267]]) tensor([268])
tensor([[  1,   2,   3,  69,   5, 155]]) tensor([156])
tensor([[  1,   2,   3, 221,   5, 222, 223, 224]]) tensor([225])
tensor([[  1,   2,   3,   4,   5, 279]]) tensor([280])
tensor([[ 1,  2,  3,  4,  5, 99]]) tensor([100])
tensor([[42, 86, 87, 88, 89, 39, 90]]) tensor([91])
tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]]) tensor([179])
tensor([[ 42, 137,   2, 226,  12,   3, 227, 228]]) tensor([155])
tensor([[10, 29,  3, 30, 31]]) tensor([32])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([23])
tensor([[ 10,  11, 157, 158, 159]]) tensor([160])
tensor([[ 42, 107,   2, 108,  19, 109]]) tensor([110])
tensor([[ 42,   2,   3, 274, 211, 275]]) tensor([276])
tensor([[ 42, 250, 251, 118, 252, 253]]) tensor([254])
tensor([[42, 18,  2, 62, 63,  3, 64, 18]]) tensor([65])
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([116])
tensor([[ 10, 308,   3, 309, 310]]) tensor([311])
tensor([[ 10,  75,   3, 296,  19, 297]]) tensor([298])
tensor([[  1,   2,   3, 141, 117,  83,   3, 277, 278]]) tensor([121])
tensor([[78, 79, 80, 81, 82, 83, 84]]) tensor([85])
tensor([[ 42, 137,   2, 138,  39, 139]]) tensor([53])
tensor([[ 42,  18,   2,   3, 281,  12,   3, 282]]) tensor([205])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([16])
tensor([[10,  2,  3, 66,  5, 67]]) tensor([68])
tensor([[ 42, 137,   2,  62,  39,   3, 322, 323]]) tensor([6])
tensor([[ 1,  2,  3, 33, 34,  5, 35]]) tensor([36])
tensor([[ 10,  75, 208]]) tensor([209])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([49])
tensor([[ 42, 318,   2,  62,  63,   3, 319,   5, 320]]) tensor([321])
tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]]) tensor([52])
tensor([[ 42, 137, 118,   3, 247,   5, 248]]) tensor([249])
tensor([[  1,   2,   3,   4,   5, 109]]) tensor([317])
tensor([[ 42,  18, 118,   3, 186, 187]]) tensor([188])
tensor([[ 1,  2,  3, 92, 93, 94]]) tensor([95])
tensor([[ 42, 290, 291, 118, 292, 158, 293, 294]]) tensor([295])
tensor([[ 78,  79, 261, 151,  14, 262, 153]]) tensor([36])
tensor([[  1,   2,   3,   4,   5, 135]]) tensor([136])
tensor([[  1,   2,   3, 146,  86,  19,  84, 192, 193]]) tensor([194])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]) tensor([72])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([28])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([61])
tensor([[ 42,  86,  87, 241, 242,  19,  39, 243]]) tensor([244])
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([74])
tensor([[  1,   2,   3,   4,   5, 236, 237]]) tensor([238])
tensor([[ 10,  29, 130, 131]]) tensor([132])
tensor([[  1,   2,   3,   4,   5, 206]]) tensor([207])
tensor([[10, 96,  3, 97]]) tensor([98])
tensor([[ 42, 216, 118, 217, 218,  19,  14, 219,  43]]) tensor([220])
tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]]) tensor([199])
tensor([[ 10,   2,  62,  63,   3, 283,   5, 284]]) tensor([285])
tensor([[ 10, 140,   3, 141, 270,  93, 271,   5,   3, 272]]) tensor([273])
tensor([[  1,   2,   3,   4,   5, 113]]) tensor([114])
tensor([[ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]]) tensor([145])
tensor([[  1,   2,   3,  50, 180, 181, 182, 183]]) tensor([184])
tensor([[ 42, 137,   2, 138,  39, 175, 269]]) tensor([99])
tensor([[  1,   2,   3, 163, 164, 165,  83,  84]]) tensor([166])
tensor([[ 42,   2,   3, 210,  17, 137, 168, 211, 169]]) tensor([113])
tensor([[  1,   2,   3,  33,  34,   5, 245]]) tensor([246])
tensor([[  1,   2,   3,  37,  38,  39, 161]]) tensor([162])
tensor([[ 10,  96,   3, 104, 239]]) tensor([240])
tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]]) tensor([36])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([9])
tensor([[  1,   2,   3,   4,   5, 286]]) tensor([287])
tensor([[ 42, 167,   2,   3,  17, 168, 169]]) tensor([170])
tensor([[ 42, 200,   2,  14, 201, 202, 203, 204]]) tensor([205])
tensor([[ 78,  79, 150, 151,  14, 152, 153]]) tensor([154])
tensor([[ 42, 117, 118,   3, 119,  94, 120]]) tensor([121])
tensor([[  1,   2,   3, 212,   5,  14, 213, 214]]) tensor([215])
tensor([[ 42, 312,   2, 313,  62,  63,   3, 314, 315]]) tensor([316])
tensor([[ 10, 140,   3, 141, 171,   5,   3,  70, 172]]) tensor([173])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([41])
tensor([[ 42, 255,   2, 256,  83, 257, 258]]) tensor([259])
tensor([[  1,   2,   3, 146, 147,  19, 148]]) tensor([149])
tensor([[ 78,  79, 288,  81,  19,  14, 289]]) tensor([85])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]) tensor([128])
tensor([[ 42, 299, 300, 118,  14, 301, 302, 158, 303, 304, 305, 306]]) tensor([307])
tensor([[ 10,  11, 189, 158, 190]]) tensor([191])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([54])
tensor([[10, 75, 76]]) tensor([77])
tensor([[ 42, 101,   2,   3,  17]]) tensor([102])
tensor([[ 1,  2,  3, 69,  5, 53]]) tensor([260])
tensor([[  1,  87, 229, 230, 231, 232]]) tensor([233])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]) tensor([185])
tensor([[ 10,  75, 111]]) tensor([112])
tensor([[  1,   2,   3, 234,   5, 235]]) tensor([131])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([124])

In [215]:
import torch.nn as nn

In [216]:
class SimpleRNN(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, 50)
    self.rnn = nn.RNN(50, 64, batch_first=True)
    self.fc = nn.Linear(64, vocab_size)

  def forward(self, question):
    embedded_question = self.embedding(question)
    hidden, final = self.rnn(embedded_question)
    output = self.fc(final.squeeze(0))

    return output

In [217]:
dataset[0][0]

tensor([1, 2, 3, 4, 5, 6])

In [218]:
embed = nn.Embedding(324, embedding_dim=50)

In [219]:
a = embed(dataset[0][0])

In [220]:
a.shape

torch.Size([6, 50])

In [221]:
rnn = nn.RNN(50, 64)

In [222]:
b = rnn(a)

In [223]:
b[0].shape

torch.Size([6, 64])

In [224]:
b[1].shape

torch.Size([1, 64])

In [225]:
fc = nn.Linear(64, 324)

In [226]:
c = fc(b[1])

In [227]:
c.shape

torch.Size([1, 324])

In [228]:
learning_rate = 0.001
epochs = 20

In [229]:
model = SimpleRNN(len(vocab))

In [230]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [231]:
# training loop
for epoch in range(epochs):

  total_loss = 0

  for question, answer in dataloader:

    optimizer.zero_grad()

    # forward pass
    output = model(question)

    # loss -> output shape (1,324) - (1)
    loss = criterion(output, answer[0])

    # gradients
    loss.backward()

    # update parameters
    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch+1}, Avg Loss: {total_loss/len(dataloader)}")

Epoch: 1, Avg Loss: 5.820882272720337
Epoch: 2, Avg Loss: 5.115199512905544
Epoch: 3, Avg Loss: 4.294067396057977
Epoch: 4, Avg Loss: 3.5090469148423935
Epoch: 5, Avg Loss: 2.898341663678487
Epoch: 6, Avg Loss: 2.3467068089379204
Epoch: 7, Avg Loss: 1.8519449048572116
Epoch: 8, Avg Loss: 1.4217510236634148
Epoch: 9, Avg Loss: 1.0742477314339745
Epoch: 10, Avg Loss: 0.8099907467762629
Epoch: 11, Avg Loss: 0.6181390325228373
Epoch: 12, Avg Loss: 0.4842589853538407
Epoch: 13, Avg Loss: 0.38196246557765534
Epoch: 14, Avg Loss: 0.3151709978779157
Epoch: 15, Avg Loss: 0.26218160217007
Epoch: 16, Avg Loss: 0.2214743105901612
Epoch: 17, Avg Loss: 0.1860801786184311
Epoch: 18, Avg Loss: 0.16299816154771382
Epoch: 19, Avg Loss: 0.14291110634803772
Epoch: 20, Avg Loss: 0.12527864111794365

In [232]:
def predict(model, question, threshold=0.5):

  # convert question to numbers
  numerical_question = text_to_indices(question, vocab)

  # tensor
  question_tensor = torch.tensor(numerical_question).unsqueeze(0)

  # send to model
  output = model(question_tensor)

  # convert logits to probs
  probs = torch.nn.functional.softmax(output, dim=1)

  # find index of max prob
  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("I don't know")

  print(list(vocab.keys())[index])

In [243]:
predict(model, "What is the largest planet in our solar system?")

jupiter